---
apiVersion: v1
kind: Service
metadata:
  name: schema-manager-server
spec:
  selector:
    app: schema-manager-server
  ports:
    - name: server
      protocol: TCP
      port: 3000
      targetPort: 3000
