---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: <platform-team-name>-stage
commonLabels:
  environment: stage
resources:
  - ../../base

patchesStrategicMerge:
  - deployment.yaml
