---
apiVersion: v1
kind: Service
metadata:
  name: <platform-team-name>-app
spec:
  selector:
    app: <platform-team-name>-app
  ports:
    - name: app
      protocol: TCP
      port: 80
      targetPort: 80
