---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-manager-server
spec:
  template:
    metadata:
      annotations:
    spec:
      containers:
        - name: adtech-adf-server
          image: europe-west1-docker.pkg.dev/uk-cti-adtech-platform-stage/schema-manager/schema-manager-server:${GIT_TAG}
