---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-manager-app
spec:
  template:
    metadata:
      annotations:
    spec:
      containers:
        - name: schema-manager-app
          image: europe-west1-docker.pkg.dev/uk-cti-adtech-platform-prod/schema-manager/schema-manager-app:${GIT_TAG}
