---
resource_types:
  - name: github-webhook-resource
    type: docker-image
    source:
      repository: europe-west1-docker.pkg.dev/uk-cti-adtech-platform-prod/adtech-platform-shared/jingkaihe/github-webhook-resource
      tag: 1.4.2
      username: _json_key
      password: |
        ((schema-manager-keyfile.keyfile))

resources:
  - name: schema-manager-server
    type: git
    icon: github
    webhook_token: ((schema-manager-server-webhook-token))
    source:
      uri: https://github.com/sky-uk/schema-manager
      paths:
        - server
      branch: main
      fetch_tags: true
      username: svc-adtech-cicd-bot
      password: ((github_pat))
  - name: schema-manager-server-webhook
    type: github-webhook-resource
    source:
      github_api: https://api.github.com
      github_token: ((github_pat))
  - name: schema-manager-server-pr-webhook
    type: github-webhook-resource
    source:
      github_api: https://api.github.com
      github_token: ((github_pat))
  - name: schema-manager-server-self-webhook
    type: github-webhook-resource
    source:
      github_api: https://api.github.com
      github_token: ((github_pat))

jobs:
  - name: schema-manager-server-set-self
    plan:
      - get: schema-manager-server
        trigger: true
      - set_pipeline: schema-manager-server-generator
        file: schema-manager-server/server/ci/pipelines/pipeline_generator.yaml
      - put: create-webhook
        resource: schema-manager-server-self-webhook
        params:
          org: sky-uk
          repo: schema-manager
          resource_name: schema-manager-server
          webhook_token: ((schema-manager-server-webhook-token))
          operation: create
          events: [push]
          pipeline: schema-manager-server-generator

  - name: schema-manager-server-pipelines
    plan:
      - get: schema-manager-server
        trigger: true
        passed: [schema-manager-server-set-self]
      - set_pipeline: schema-manager-server-pr
        file: schema-manager-server/server/ci/pipelines/check.yaml
      - set_pipeline: schema-manager-server-deploy
        file: schema-manager-server/server/ci/pipelines/deploy.yaml
      - put: create-webhook
        resource: schema-manager-server-webhook
        params:
          org: sky-uk
          repo: schema-manager
          resource_name: schema-manager-server
          webhook_token: ((schema-manager-server-webhook-token))
          operation: create
          events: [push]
          pipeline: schema-manager-server-deploy
      - put: create-webhook-pr
        resource: schema-manager-server-pr-webhook
        params:
          org: sky-uk
          repo: schema-manager
          resource_name: schema-manager-server-pr
          webhook_token: ((schema-manager-server-webhook-token))
          operation: create
          events: [pull_request]
          pipeline: schema-manager-server-pr
