---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: europe-west1-docker.pkg.dev/uk-cti-adtech-platform-prod/adtech-platform-shared/concourse/git-resource
    tag: alpine
    username: _json_key
    password: |
      ((<platform-keyfile-name>.keyfile))
inputs:
  - name: ((repo_name))
outputs:
  - name: ((repo_name))
run:
  path: /bin/sh
  args:
    - -c
    - |
      chmod +x server/ci/scripts/tag.sh
      COMMIT_SHA=$(git rev-parse HEAD)
      GIT_COMMIT=$COMMIT_SHA ./server/ci/scripts/tag.sh
  dir: ((repo_name))
params:
  PAT_TOKEN: ((pat_token))
  REPO_NAME: ((repo_name))
